const foodServings = {
    1200: {
        'Grains': '4-5',
        'Vegetables': '3-4',
        'Fruits': '3-4',
        'Fats and Oils': '1',
        'Low Fat Dairy Products': '2-3',
        'Lean meats, poultry, and fish': '3 or less',
        'Nuts, seeds, and legumes': '3 per week',
        'Sweets and added sugars': '3 or less per week',
        'Maximum Sodium Limit': '2,300 mg',
    },
    1400: {
        'Grains': '5-6',
        'Vegetables': '3-4',
        'Fruits': '4',
        'Fats and Oils': '1',
        'Low Fat Dairy Products': '2-3',
        'Lean meats, poultry, and fish': '3-4 or less',
        'Nuts, seeds, and legumes': '3 per week',
        'Sweets and added sugars': '3 or less per week',
        'Maximum Sodium Limit': '2,300 mg',
    },
    1600: {
        'Grains': '6',
        'Vegetables': '3-4',
        'Fruits': '4',
        'Fats and Oils': '2',
        'Low Fat Dairy Products': '2-3',
        'Lean meats, poultry, and fish': '3-4 or less',
        'Nuts, seeds, and legumes': '3-4 per week',
        'Sweets and added sugars': '3 or less per week',
        'Maximum Sodium Limit': '2,300 mg',
    },
    1800: {
        'Grains': '6',
        'Vegetables': '4-5',
        'Fruits': '4-5',
        'Fats and Oils': '2-3',
        'Low Fat Dairy Products': '2-3',
        'Lean meats, poultry, and fish': '6 or less',
        'Nuts, seeds, and legumes': '4 per week',
        'Sweets and added sugars': '5 or less per week',
        'Maximum Sodium Limit': '2,300 mg',
    },
    2000: {
        'Grains': '6-8',
        'Vegetables': '4-5',
        'Fruits': '4-5',
        'Fats and Oils': '2-3',
        'Low Fat Dairy Products': '2-3',
        'Lean meats, poultry, and fish': '6 or less',
        'Nuts, seeds, and legumes': '4-5 per week',
        'Sweets and added sugars': '5 or less per week',
        'Maximum Sodium Limit': '2,300 mg',
    },
    2600: {
        'Grains': '10-11',
        'Vegetables': '5-6',
        'Fruits': '5-6',
        'Fats and Oils': '3',
        'Low Fat Dairy Products': '3',
        'Lean meats, poultry, and fish': '6 or less',
        'Nuts, seeds, and legumes': '1',
        'Sweets and added sugars': '2 or less',
        'Maximum Sodium Limit': '2,300 mg',
    },
    3100: {
        'Grains': '12-13',
        'Vegetables': '6',
        'Fruits': '6',
        'Fats and Oils': '4',
        'Low Fat Dairy Products': '3-4',
        'Lean meats, poultry, and fish': '6-9',
        'Nuts, seeds, and legumes': '1',
        'Sweets and added sugars': '2 or less',
        'Maximum Sodium Limit': '2,300 mg',
    },
}

export default foodServings;